SURVIVORS = [
    'Dwight',
    'Meg',
    'Claudette',
    'Jake',
    'Jeff',
    'Nea',
    'Bill',
    'David',
    'Laurie',
    'Ace',
    'Feng',
    'Quentin',
    'Tapp',
    'Kate',
    'Francis',
    'Jane',
    'Ash',
    'Nancy',
    'Steve',
    'Kimura',
    'Zarina',
    'Cheryl',
    'Felix',
    'Elodie'
]

KILLERS = [
    'Clown',
    'Doctor',
    'Freddy',
    'Hag',
    'Hillbilly',
    'Huntress',
    'Leatherface',
    'Legion',
    'Myers',
    'Nurse',
    'Pig',
    'Spirit',
    'Trapper',
    'Wraith',
    'Plague',
    'Ghostface',
    'Demogorgon',
    'Oni',
    'Deathslinger',
    'Executioner',
    'Blight'
]

KILLER_PERKS = [
    'Agitation',
    'Nurses Calling',
    'Bamboozle',
    'BBQ And Chili',
    'Beast Of Prey',
    'Bitter Murmur',
    'Bloodhound',
    'Blood Warden',
    'Brutal Strength',
    'Coulrophobia',
    'Deerstalker',
    'Devour Hope',
    'Discordance',
    'Distressing',
    'Dying Light',
    'Enduring',
    'Fire Up',
    'Franklins Loss',
    'Generator Overcharge',
    'Hangmans Trick',
    'Hatred',
    'Haunted Ground',
    'Huntress Lullaby',
    'Insidious',
    'Iron Grasp',
    'Iron Maiden',
    'Knock Out',
    'Lightborn',
    'Mad Grit',
    'Make Your Choice',
    'Monitor And Abuse',
    'Monstrous Shrine',
    'No One Escapes Death',
    'Overwhelming Presence',
    'Play With Your Food',
    'Pop Goes The Weasel',
    'Predator',
    'Remember Me',
    'Ruin',
    'Save The Best For Last',
    'Shadowborn',
    'Sloppy Butcher',
    'Spies From The Shadows',
    'Spirit Fury',
    'Stridor',
    'Surveillance',
    'Territorial Imperative',
    'Thatanophobia',
    'The Third Seal',
    'Thrill Of The Hunt',
    'Tinkerer',
    'Unnerving Presence',
    'Unrelenting',
    'Whispers',
    'Corrupt Intervention',
    'Infectious Fright',
    'Dark Devotion',
    'Furtive Chase',
    'Im All Ears',
    'Thrilling Tremors',
    'Crue lLimits',
    'Mind Breaker',
    'Surge',
    'Blood Echo',
    'Nemesis',
    'Zanshin Tactics',
    'Dead Man Switch',
    'Gear Head',
    'Hex Retribution',
    'Deathbound',
    'Forced Penance',
    'Trail Of Torment',
    'Dragons Grip',
    'Hex Blood Favor',
    'Hex Undying'
]

SURVIVOR_PERKS = {
    'Ace In The Hole': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/24/IconPerks_aceInTheHole.png/revision/latest?cb=20161208214510',
    'Adrenaline': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f7/IconPerks_adrenaline.png/revision/latest?cb=20160605204801',
    'Aftercare': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0d/IconPerks_aftercare.png/revision/latest?cb=20181128100931',
    'Alert': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/71/IconPerks_alert.png/revision/latest?cb=20170511153335',
    'Autodidact': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/96/IconPerks_autodidact.png/revision/latest?cb=20180828173011',
    'Balanced Landing': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5e/IconPerks_balancedLanding.png/revision/latest?cb=20160821133918',
    'Boil Over': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f5/IconPerks_boilOver.png/revision/latest?cb=20180529195012',
    'Bond': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a0/IconPerks_bond.png/revision/latest?cb=20160605204830',
    'Borrowed Time': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a3/IconPerks_borrowedTime.png/revision/latest?cb=20170308184730',
    'Botany Knowledge': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1e/IconPerks_botanyKnowledge.png/revision/latest?cb=20160605204836',
    'Breakdown': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6c/IconPerks_breakdown.png/revision/latest?cb=20181128100926',
    'Calm Spirit': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6c/IconPerks_calmSpirit.png/revision/latest?cb=20160605204847',
    'Dance With Me': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/17/IconPerks_danceWithMe.png/revision/latest?cb=20180529195003',
    'Dark Sense': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/92/IconPerks_darkSense.png/revision/latest?cb=20160605204853',
    'Dead Hard': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/75/IconPerks_deadHard.png/revision/latest?cb=20170727160956',
    'Decisive Strike': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/ee/IconPerks_decisiveStrike.png/revision/latest?cb=20161023112852',
    'Deja Vu': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/89/IconPerks_dejaVu.png/revision/latest?cb=20160605204905',
    'Deliverance': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7e/IconPerks_deliverance.png/revision/latest?cb=20180828173004',
    'Detectives Hunch': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7b/IconPerks_detectivesHunch.png/revision/latest?cb=20180123224231',
    'Distortion': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/41/IconPerks_distortion.png/revision/latest?cb=20181128100914',
    'Diversion': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a6/IconPerks_diversion.png/revision/latest?cb=20180828172956',
    'Empathy': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/ae/IconPerks_empathy.png/revision/latest?cb=20160605204916',
    'Hope': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/18/IconPerks_hope.png/revision/latest?cb=20160605204928',
    'Iron Will': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/58/IconPerks_ironWill.png/revision/latest?cb=20160605204945',
    'Kindred': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a8/IconPerks_kindred.png/revision/latest?cb=20160819130530',
    'Leader': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3d/IconPerks_leader.png/revision/latest?cb=20160605204957',
    'Left Behind': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c3/IconPerks_leftBehind.png/revision/latest?cb=20170308184910',
    'Lightweight': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/67/IconPerks_lightweight.png/revision/latest?cb=20160605205008',
    'Lithe': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/cc/IconPerks_lithe.png/revision/latest?cb=20170511153301',
    'No Mither': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f5/IconPerks_noMither.png/revision/latest?cb=20170727161003',
    'No One Left Behind': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b0/IconPerks_noOneLeftBehind.png/revision/latest?cb=20160605205026',
    'Object Of Obsession': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2b/IconPerks_objectOfObsession.png/revision/latest?cb=20161023112952',
    'Open Handed': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5d/IconPerks_open-Handed.png/revision/latest?cb=20161210091243',
    'Pharmacy': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f1/IconPerks_pharmacy.png/revision/latest?cb=20171026230450',
    'Plunderers Instinct': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/28/IconPerks_plunderersInstinct.png/revision/latest?cb=20160605205031',
    'Premonition': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/39/IconPerks_premonition.png/revision/latest?cb=20160605205043',
    'Prove Thyself': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0f/IconPerks_proveThyself.png/revision/latest?cb=20160605205049',
    'Quick And Quiet': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/14/IconPerks_quickAndQuiet.png/revision/latest?cb=20160605205055',
    'Resilience': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/ee/IconPerks_resilience.png/revision/latest?cb=20160605205100',
    'Saboteur': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0e/IconPerks_saboteur.png/revision/latest?cb=20200220105714',
    'Self Care': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f1/IconPerks_selfCare.png/revision/latest?cb=20160605205112',
    'Slippery Meat': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/03/IconPerks_slipperyMeat.png/revision/latest?cb=20201105152240',
    'Small Game': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/dc/IconPerks_smallGame.png/revision/latest?cb=20160605205135',
    'Sole Survivor': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/8e/IconPerks_soleSurvivor.png/revision/latest?cb=20161023113045',
    'Spine Chill': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/57/IconPerks_spineChill.png/revision/latest?cb=20160605205147',
    'Sprint Burst': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/e4/IconPerks_sprintBurst.png/revision/latest?cb=20160605205153',
    'Stake Out': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/cd/IconPerks_stakeOut.png/revision/latest?cb=20180123224338',
    'Streetwise': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/ff/IconPerks_streetwise.png/revision/latest?cb=20160821134155',
    'Technician': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/62/IconPerks_technician.png/revision/latest?cb=20170511153221',
    'Tenacity': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9d/IconPerks_tenacity.png/revision/latest?cb=20180123224404',
    'This Is Not Happening': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/58/IconPerks_thisIsNotHappening.png/revision/latest?cb=20160605205158',
    'Unbreakable': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4a/IconPerks_unbreakable.png/revision/latest?cb=20170308184922',
    'Up The Ante': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a3/IconPerks_upTheAnte.png/revision/latest?cb=20161210091356',
    'Urban Evasion': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c7/IconPerks_urbanEvasion.png/revision/latest?cb=20160821134257',
    'Vigil': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/46/IconPerks_vigil.png/revision/latest?cb=20171026230511',
    'Wake Up': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/fd/IconPerks_wakeUp.png/revision/latest?cb=20171026230520',
    'Well Make It': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/8a/IconPerks_wellMakeIt.png/revision/latest?cb=20160605205228',
    'Were Gonna Live Forever': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b8/IconPerks_wereGonnaLiveForever.png/revision/latest?cb=20170727160948',
    'Windows Of Opportunity': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/17/IconPerks_windowsOfOpportunity.png/revision/latest?cb=20180529195008',
    'Head On': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/cb/IconPerks_headOn.png/revision/latest?cb=20190308175420',
    'Poised': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/52/IconPerks_poised.png/revision/latest?cb=20190308175429',
    'Solidarity': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9e/IconPerks_solidarity.png/revision/latest?cb=20190308175435',
    'Buckle Up': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/74/IconPerks_buckleUp.png/revision/latest?cb=20190402180455',
    'Flip Flop': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/31/IconPerks_flip-Flop.png/revision/latest?cb=20190402180450',
    'Mettle Of Man': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/52/IconPerks_mettleOfMan.png/revision/latest?cb=20190402180459',
    'Baby Sitter': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/db/IconPerks_babysitter.png/revision/latest?cb=20190903174955',
    'Better Together': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/02/IconPerks_betterTogether.png/revision/latest?cb=20190903175013',
    'Camaraderie': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1d/IconPerks_camaraderie.png/revision/latest?cb=20190903175027',
    'Fixated': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7c/IconPerks_fixated.png/revision/latest?cb=20190903175127',
    'Inner Strength': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/47/IconPerks_innerStrength.png/revision/latest?cb=20190903175147',
    'Second Wind': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/97/IconPerks_secondWind.png/revision/latest?cb=20190903175238',
    'Any Means Necessary': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/79/IconPerks_anyMeansNecessary.png/revision/latest?cb=20191126213542',
    'Breakout': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d0/IconPerks_breakout.png/revision/latest?cb=20191126213552',
    'Lucky Break': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a7/IconPerks_luckyBreak.png/revision/latest?cb=20191126213558',
    'For The People': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/31/IconPerks_forThePeople.png/revision/latest?cb=20200218172919',
    'Off The Record': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9e/IconPerks_offTheRecord.png/revision/latest?cb=20200218172747',
    'Red Herring': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1c/IconPerks_redHerring.png/revision/latest?cb=20200218172728',
    'Blood Pact': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c9/IconPerks_bloodPact.png/revision/latest?cb=20200526201448',
    'Repressed Alliance': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/31/IconPerks_repressedAlliance.png/revision/latest?cb=20200526201745',
    'Soul Guard': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a5/IconPerks_soulGuard.png/revision/latest?cb=20200526201807',
    'Visionary': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7c/IconPerks_visionary.png/revision/latest?cb=20200819113857',
    'BuiltToLast': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3b/IconPerks_builtToLast.png/revision/latest?cb=20200819114105',
    'Desperate Measures': 'https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/84/IconPerks_desperateMeasures.png/revision/latest?cb=20200819113949'
}